# Generated by Django 4.1.13 on 2026-06-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка/Фото'),
        ),
    ]
